(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ansi-color-names-vector ["#242424" "#e5786d" "#95e454" "#cae682" "#8ac6f2" "#333366" "#ccaa8f" "#f6f3e8"])
 '(confirm-kill-emacs (quote y-or-n-p))
 '(css-indent-level 2)
 '(css-indent-offset 2)
 '(custom-enabled-themes (quote (misterioso)))
 '(custom-safe-themes (quote ("7fe1e3de3e04afc43f9a3d3a8d38cd0a0efd9d4c" "d14db41612953d22506af16ef7a23c4d112150e5" "517aecb1202bfa31fd3c44473d72483c5166124d" "2bfbc800988b899e101edd59f601ab530ea97686" "5600dc0bb4a2b72a613175da54edb4ad770105aa" "68022c474ffb440be956540dbe95bfd42655620e" "ce3e74cb8944681667c3d9a87f4b7498412f476e" default)))
 '(display-time-mode t)
 '(elscreen-display-tab nil)
 '(emux-completing-read-command (quote ido-completing-read))
 '(fill-column 90)
 '(fringe-mode nil nil (fringe))
 '(global-linum-mode t)
 '(grep-command "grep -nH -e ")
 '(grep-find-command nil)
 '(grep-find-template "find . <X> -type f <F> -exec grep <C> -nHI -e <R> {} +")
 '(grep-highlight-matches (quote auto))
 '(grep-template "grep <X> <C> -nH -e <R> <F>")
 '(grep-use-null-device nil)
 '(highline-selected-window t)
 '(ido-auto-merge-delay-time 3)
 '(ido-enable-flex-matching t)
 '(ido-everywhere t)
 '(indent-tabs-mode t)
 '(indicate-buffer-boundaries (quote left))
 '(indicate-empty-lines t)
 '(initial-buffer-choice t)
 '(iswitchb-use-virtual-buffers t nil (recentf))
 '(js-indent-level 2)
 '(js2-auto-indent-p nil)
 '(js2-basic-offset 2)
 '(js2-bounce-indent-p t)
 '(js2-mirror-mode nil)
 '(kill-ring-max 200)
 '(kill-whole-line t)
 '(linum-delay t)
 '(linum-eager t)
 '(magit-commit-all-when-nothing-staged (quote ask-stage))
 '(magit-completing-read-function (quote ido-completing-read))
 '(magit-process-popup-time 0)
 '(magit-save-some-buffers nil)
 '(nxml-child-indent 2)
 '(nxml-outline-child-indent 2)
 '(quote (sgml-basic-offset 4))
 '(scss-compile-at-save nil)
 '(show-paren-mode t)
 '(tab-width 2)
 '(uniquify-buffer-name-style (quote forward) nil (uniquify))
 '(yank-pop-change-selection t))

(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(magit-diff-add ((t (:foreground "green3"))))
 '(magit-item-highlight ((t (:background "RoyalBlue4")))))
